OpenDialogue/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
import OpenDialogue.views as core_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', core_views.home, name='home'),
    path('authentication/', include('authentication.urls'), name='authentication'),
    path('forum/', include('forum.urls'), name='forum')
]

OpenDiscussion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
import OpenDiscussion.views as core_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', core_views.home, name='home'),
    path('authentication/', include('authentication.urls'), name='authentication'),
    path('forum/', include('forum.urls'), name='forum'),
    path('about/', core_views.about, name='about')
]

account/urls.py
from django.urls import path

from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'account'
urlpatterns = [
    path('login', LoginView.as_view(template_name="login.html"), name='login'),
    path('signup', views.signup, name='signup'),
    path('logout', LogoutView.as_view(template_name='logged_out.html'), name='logout'),
]

authentication/urls.py
from django.urls import path

from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'authentication'
urlpatterns = [
    path('login', LoginView.as_view(template_name="login.html"), name='login'),
    path('signup', views.signup, name='signup'),
    path('logout', LogoutView.as_view(next_page='home'), name='logout'),
]

forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'
urlpatterns = [
    path('', views.index, name='index'),
    path('write_post', views.write_post, name='write_post'),
    path('respond_post/<postid>', views.respond_post, name='respond_post'),
    path('post_successful', views.post_successful, name='post_successful'),
    path('post/<postid>', views.post, name='post'),
    path('agree/<postid>', views.agree, name='agree'),
    path('disagree/<postid>', views.disagree, name='disagree'),
    path('strong/<postid>', views.strong, name='strong'),
    path('weak/<postid>', views.weak, name='weak'),
    path('explore', views.explore, name='explore'),
    path('account/<searchusername>', views.account, name='account'),
]

forum/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="author")
    title = models.CharField(max_length=500)
    content = models.TextField(max_length=20000)
    created = models.DateTimeField()
    parent = models.ForeignKey("Post", on_delete=models.CASCADE, related_name="postparent", blank=True, null=True)
    parentid = models.IntegerField(blank=True, null=True)
    parenttitle = models.CharField(blank=True, max_length=500)
    parentauthor = models.CharField(blank=True, max_length=100)
    
    views = models.IntegerField(default=0)
    agrees = models.IntegerField(default=0)
    agreechecks = models.IntegerField(default=0)
    strongs = models.IntegerField(default=0)
    strongchecks = models.IntegerField(default=0)

class UserWrapper(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    viewed = models.ManyToManyField(Post, related_name='viewed', blank=True)
    agreed = models.ManyToManyField(Post, related_name='agreed', blank=True)
    disagreed = models.ManyToManyField(Post, related_name='disagreed', blank=True)
    stronged = models.ManyToManyField(Post, related_name='stronged', blank=True)
    weaked = models.ManyToManyField(Post, related_name='weaked', blank=True)
    reputation = models.IntegerField(default=0)

forum/forms.py
from django import forms

class PostForm(forms.Form):
    title = forms.CharField(max_length=500, widget=forms.TextInput(attrs={'size':150}))
    content = forms.CharField(min_length=2000, max_length=20000, widget=forms.Textarea(attrs={'rows':25, 'cols':200}))

forum/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import Permission, User
from forum.models import Post, UserWrapper
from forum.forms import PostForm
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist

import datetime

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return redirect('home')
    if request.user.is_authenticated:
        context = {"current_page": "index"}
        context['user'] = request.user
        context['posts'] = Post.objects.all().order_by("-views")[:5]
        return render(request, "index.html", context)
    else:
        return redirect('home')

def write_post(request):
    if not request.user.is_authenticated:
        return redirect('home')
    if request.method == "POST":
        title = request.POST.get("title")
        content = request.POST.get("content")
        author = request.user
        new_post = Post(author=author, title=title, content=content, created=datetime.datetime.now())
        new_post.save()
        return redirect('forum:post_successful')
    else:
        context = {"current_page": "write_post"}
        context['user'] = request.user
        context["form"] = PostForm()
        return render(request, "write_post.html", context)

def post_successful(request):
    if not request.user.is_authenticated:
        return redirect('home')
    context = {}
    context['user'] = request.user
    return render(request, "post_successful.html", context)

def post(request, postid):
    if not request.user.is_authenticated:
        return redirect('home')
    context = {}
    context['user'] = request.user
    thepost = Post.objects.get(id=postid)
    context['post'] = thepost
    UserWrapper.objects.get_or_create(user=request.user)
    if not UserWrapper.objects.filter(user=request.user).filter(viewed=thepost).exists():
        thepost.views += 1
        thepost.save()
        UserWrapper.objects.get(user=request.user).viewed.add(thepost)
    if UserWrapper.objects.filter(user=request.user).filter(agreed=thepost).exists():
        context['agreed'] = True
    else:
        context['agreed'] = False
    if UserWrapper.objects.filter(user=request.user).filter(disagreed=thepost).exists():
        context['disagreed'] = True
    else:
        context['disagreed'] = False
    if UserWrapper.objects.filter(user=request.user).filter(stronged=thepost).exists():
        context['stronged'] = True
    else:
        context['stronged'] = False
    if UserWrapper.objects.filter(user=request.user).filter(weaked=thepost).exists():
        context['weaked'] = True
    else:
        context['weaked'] = False
    context['responses'] = Post.objects.get(id=postid).postparent.all()
        
    return render(request, "post.html", context)

def explore(request):
    if not request.user.is_authenticated:
        return redirect('home')
        
    context = {"current_page": "explore"}
    context['user'] = request.user
    if request.method == "POST":
        query = request.POST.get("query")
        sortby = request.POST.get("sortby")
        context['posts'] = Post.objects.filter(\
            Q(author__username__icontains=query) |\
                Q(title__icontains=query) |\
                    Q(content__icontains=query))
        if sortby == "date":
            context['posts'] = context['posts'].order_by('-created')
        elif sortby == "alpha":
            context['posts'] = context['posts'].order_by('title')
        elif sortby == "views":
            context['posts'] = context['posts'].order_by('-views')
        return render(request, "explore.html", context)
    else:
        context['posts'] = []
        return render(request, "explore.html", context)

def account(request, searchusername):
    if not request.user.is_authenticated:
        return redirect('home')
    context = {}
    context['user'] = request.user
    context['searcheduser'] = User.objects.get(username=searchusername)
    context['posts'] = Post.objects.filter(Q(author__username=searchusername))
    context['totalviews'] = sum(post.views for post in context['posts'])
    return render(request, "account.html", context)

def agree(request, postid):
    if not request.user.is_authenticated:
        return redirect('home')
    context = {}
    context['user'] = request.user
    thepost = Post.objects.get(id=postid)
    UserWrapper.objects.get_or_create(user=request.user)
    if not UserWrapper.objects.filter(user=request.user).filter(agreed=thepost).exists():
        thepost.agrees += 1
        if not UserWrapper.objects.filter(user=request.user).filter(disagreed=thepost).exists():
            thepost.agreechecks += 1
        else:
            UserWrapper.objects.get(user=request.user).disagreed.remove(thepost)
        thepost.save()
        UserWrapper.objects.get(user=request.user).agreed.add(thepost)
    return redirect('forum:post', postid=postid)

def disagree(request, postid):
    if not request.user.is_authenticated:
        return redirect('home')
    context = {}
    context['user'] = request.user
    thepost = Post.objects.get(id=postid)
    UserWrapper.objects.get_or_create(user=request.user)
    if not UserWrapper.objects.filter(user=request.user).filter(disagreed=thepost).exists():
        if not UserWrapper.objects.filter(user=request.user).filter(agreed=thepost).exists():
            thepost.agreechecks += 1
        else:
            thepost.agrees -= 1
            UserWrapper.objects.get(user=request.user).agreed.remove(thepost)
        thepost.save()
        UserWrapper.objects.get(user=request.user).disagreed.add(thepost)
    return redirect('forum:post', postid=postid)

def strong(request, postid):
    if not request.user.is_authenticated:
        return redirect('home')
    context = {}
    context['user'] = request.user
    thepost = Post.objects.get(id=postid)
    UserWrapper.objects.get_or_create(user=request.user)
    if not UserWrapper.objects.filter(user=request.user).filter(stronged=thepost).exists():
        thepost.strongs += 1
        if not UserWrapper.objects.filter(user=request.user).filter(weaked=thepost).exists():
            thepost.strongchecks += 1
        else:
            UserWrapper.objects.get(user=request.user).weaked.remove(thepost)
        thepost.save()
        UserWrapper.objects.get(user=request.user).stronged.add(thepost)
    return redirect('forum:post', postid=postid)

def weak(request, postid):
    if not request.user.is_authenticated:
        return redirect('home')
    context = {}
    context['user'] = request.user
    thepost = Post.objects.get(id=postid)
    UserWrapper.objects.get_or_create(user=request.user)
    if not UserWrapper.objects.filter(user=request.user).filter(weaked=thepost).exists():
        if not UserWrapper.objects.filter(user=request.user).filter(stronged=thepost).exists():
            thepost.strongchecks += 1
        else:
            thepost.strongs -= 1
            UserWrapper.objects.get(user=request.user).stronged.remove(thepost)
        thepost.save()
        UserWrapper.objects.get(user=request.user).weaked.add(thepost)
    return redirect('forum:post', postid=postid)

def respond_post(request, postid):
    if not request.user.is_authenticated:
        return redirect('home')
    if request.method == "POST":
        title = request.POST.get("title")
        content = request.POST.get("content")
        author = request.user
        parent = Post.objects.get(id=postid)
        new_post = Post(author=author, title=title, content=content, created=datetime.datetime.now(), parent=parent, parentid=postid, parenttitle=parent.title, parentauthor=parent.author)
        new_post.save()
        return redirect('forum:post_successful')
    else:
        context = {}
        context['user'] = request.user
        context['form'] = PostForm()
        context['parent'] = Post.objects.get(id=postid)
        return render(request, "respond_post.html", context)

forum/templates/account.html
{% extends 'base.html' %}

{% block content %}
{% include "navbar.html" %}
<h1><b>Account page:</b> {{ searcheduser.username }}</h1>
<table style="width:100%;">
    <tr>
        <td>
            <p><b>🎂 Joined on:</b> {{ searcheduser.date_joined }}</p>
            <p><b>👁️ Total views:</b> {{ totalviews }}</p>
        </td>
        <td>
            <p><b>👍 Average agreement rating:</b> 89%</p>
            <p><b>💪 Average strength rating:</b> 56%</p>
        </td>
    </tr>
</table>
<h2>Posts made by {{ searcheduser.username }} ({{ posts | length }}):</h2>
{% if posts|length == 0 %}
<p>No posts yet</p>
{% endif %}
{% for post in posts %}
<div class="post_box" onclick='location.href="{% url 'forum:post' post.id %}";'>
    <h2>{{post.title}}
    {% if post.parentid != None %}<br><div style="font-size: 20px">⮨ Responding to <a href="{% url 'forum:post' post.parentid %}">"{{ post.parenttitle }}"</a> by <a href="{% url 'forum:account' post.parentauthor %}">{{ post.parentauthor }}</a></div>{% endif %}
    </h2>
    <p><i>By <a href="{% url 'forum:account' post.author %}">{{post.author}}</a> on {{post.created}}</i></p>
    <p>{% with broken=post.content|linebreaks %}{{broken|truncatechars:300}}{% endwith %}</p>
    <p>——<br><i>👁️ {{post.views}} views</i>
    {% if post.agreechecks > 0 %} &ensp;•&ensp; <i>👍 {% widthratio post.agrees post.agreechecks 100 %}% agree with this</i> {% endif %}
    {% if post.strongchecks > 0 %} &ensp;•&ensp; <i>💪 {% widthratio post.strongs post.strongchecks 100 %}% think this was a strong argument</i> {% endif %}
    </p>
</div>
<br>
{% endfor %}
{% endblock %}

forum/templates/explore.html
{% extends 'base.html' %}

{% block content %}
{% include "navbar.html" %}
<h1>Explore</h1>
<form action="{% url 'forum:explore' %}" method="post">
    {% csrf_token %}
    <p>Search posts:</p>
    <input id="query" type="text" name="query" style="width:500px" required="required">
    <p>Sort results by:</p>
    <select class="customSelect" name="sortby" id="sortby" style="width:500px">
        <option value="date">Date published</option>
        <option value="alpha">Alphabetical</option>
        <option value="views">Views</option>
    </select>
    <br><br>
    <input class="fancyButton" type="submit" value="OK">
</form>
{% for post in posts %}
<div class="post_box" onclick='location.href="{% url 'forum:post' post.id %}";'>
    <h2>{{post.title}}
    {% if post.parentid != None %}<br><div style="font-size: 20px">⮨ Responding to <a href="{% url 'forum:post' post.parentid %}">"{{ post.parenttitle }}"</a> by <a href="{% url 'forum:account' post.parentauthor %}">{{ post.parentauthor }}</a></div>{% endif %}
    </h2>
    <p><i>By <a href="{% url 'forum:account' post.author %}">{{post.author}}</a> on {{post.created}}</i></p>
    <p>{% with broken=post.content|linebreaks %}{{broken|truncatechars:300}}{% endwith %}</p>
    <p>——<br><i>👁️ {{post.views}} views</i>
    {% if post.agreechecks > 0 %} &ensp;•&ensp; <i>👍 {% widthratio post.agrees post.agreechecks 100 %}% agree with this</i> {% endif %}
    {% if post.strongchecks > 0 %} &ensp;•&ensp; <i>💪 {% widthratio post.strongs post.strongchecks 100 %}% think this was a strong argument</i> {% endif %}
    </p>
</div>
<br>
{% endfor %}
{% endblock %}

forum/templates/index.html
{% extends 'base.html' %}

{% block content %}
{% include "navbar.html" %}
<h1>Recommended</h1>
{% for post in posts %}
<div class="post_box" onclick='location.href="{% url 'forum:post' post.id %}";'>
    <h2>{{post.title}}
    {% if post.parentid != None %}<br><div style="font-size: 20px">⮨ Responding to <a href="{% url 'forum:post' post.parentid %}">"{{ post.parenttitle }}"</a> by <a href="{% url 'forum:account' post.parentauthor %}">{{ post.parentauthor }}</a></div>{% endif %}
    </h2>
    <p><i>By <a href="{% url 'forum:account' post.author %}">{{post.author}}</a> on {{post.created}}</i></p>
    <p>{% with broken=post.content|linebreaks %}{{broken|truncatechars:300}}{% endwith %}</p>
    <p>——<br><i>👁️ {{post.views}} views</i>
    {% if post.agreechecks > 0 %} &ensp;•&ensp; <i>👍 {% widthratio post.agrees post.agreechecks 100 %}% agree with this</i> {% endif %}
    {% if post.strongchecks > 0 %} &ensp;•&ensp; <i>💪 {% widthratio post.strongs post.strongchecks 100 %}% think this was a strong argument</i> {% endif %}
    </p>
</div>
<br>
{% endfor %}
{% endblock %}

forum/templates/navbar.html
{% block content %}
<div class="ulGray">
    <li style="float: left;"><a href="{% url 'forum:index' %}">Feed</a></li>
    <li style="float: left;"><a href="{% url 'forum:write_post' %}">Write a post</a></li>
    <li style="float: left;"><a href="{% url 'forum:search' %}">Search posts</a></li>
    <li style="float: right;"><a href="{% url 'authentication:logout' %}">Log out</a></li>
    <li style="float: right;"><a href="#">Logged in as {{ user.username }}</a></li>
</div>
{% endblock %}

forum/templates/post.html
{% extends 'base.html' %}

{% block content %}
{% include "navbar.html" %}
<h1>{{post.title}}
{% if post.parentid != None %}<br><div style="font-size: 20px; color:gray">⮨ Responding to <a href="{% url 'forum:post' post.parentid %}">"{{ post.parenttitle }}"</a> by <a href="{% url 'forum:account' post.parentauthor %}">{{ post.parentauthor }}</a></div>{% endif %}
</h1>
<p><i>By <a href="{% url 'forum:account' post.author %}">{{post.author}}</a> on {{post.created}}</i></p>
<p>{{ post.content|linebreaks }}</p>
<p>——<br>
<i>👁️ {{post.views}} views<br>
👍 {% if post.agreechecks > 0 %}
{% widthratio post.agrees post.agreechecks 100 %}% agree with this
{% else %}
Be the first to agree or disagree!
{% endif %}
<a href="{% url 'forum:agree' post.id %}" style="{% if agreed %}color: limegreen{% else %}color: lightgray{% endif %}; text-decoration: none;">▲</a>&ensp;
<a href="{% url 'forum:disagree' post.id %}" style="{% if disagreed %}color: red{% else %}color: lightgray{% endif %}; text-decoration: none;">▼</a>
<br>
💪 {% if post.strongchecks > 0 %}
{% widthratio post.strongs post.strongchecks 100 %}% think this was a strong argument
{% else %}
Be the first to judge the article as strong or weak!
{% endif %}
<a href="{% url 'forum:strong' post.id %}" style="{% if stronged %}color: limegreen{% else %}color: lightgray{% endif %}; text-decoration: none;">▲</a>&ensp;
<a href="{% url 'forum:weak' post.id %}" style="{% if weaked %}color: red{% else %}color: lightgray{% endif %}; text-decoration: none;">▼</a>
</i>
</p>
<h2>Responses:</h2>
<p><a href="{% url 'forum:respond_post' post.id %}" style="text-decoration: none;">⮨ Respond to this post.</a></p>
{% if responses|length == 0 %}
<p>No responses yet</p>
{% endif %}
{% for post in responses %}
<div class="post_box" onclick='location.href="{% url 'forum:post' post.id %}";'>
    <h2>{{post.title}}</h2>
    <p><i>By <a href="{% url 'forum:account' post.author %}">{{post.author}}</a> on {{post.created}}</i></p>
    <p>{% with broken=post.content|linebreaks %}{{broken|truncatechars:300}}{% endwith %}</p>
    <p>——<br><i>👁️ {{post.views}} views</i>
    {% if post.agreechecks > 0 %} &ensp;•&ensp; <i>👍 {% widthratio post.agrees post.agreechecks 100 %}% agree with this</i> {% endif %}
    {% if post.strongchecks > 0 %} &ensp;•&ensp; <i>💪 {% widthratio post.strongs post.strongchecks 100 %}% think this was a strong argument</i> {% endif %}
    </p>
</div>
<br>
{% endfor %}
{% endblock %}

forum/templates/post_successful.html
{% extends 'base.html' %}

{% block content %}
{% include "navbar.html" %}
<p>Post successful.</p>
{% endblock %}

forum/templates/respond_post.html
{% extends 'base.html' %}

{% block content %}
{% include "navbar.html" %}
<h1>Respond to a Post</h1>
<p><b>Responding to <a href="{% url 'forum:post' parent.id %}">"{{ parent.title }}"</a> by <a href="{% url 'forum:account' parent.author %}">{{ parent.author }}</a></b></p>
<form name="myForm" action="{% url 'forum:respond_post' parent.id %}" method="POST">
    {% csrf_token %}
    <p>Post title: {{ form.title }}</p>
    <p>Post content: (min length 2000 char, max 20000)<br>{{ form.content }}</p>
    <input type="submit" class="fancyButton" value="Submit" onclick="return checkForm();" style="font-size: large">
</form>
{% endblock %}

forum/templates/search.html
{% extends 'base.html' %}

{% block content %}
{% include "navbar.html" %}
<h1>Search posts</h1>
<form action="{% url 'forum:search' %}" method="post">
    {% csrf_token %}
    <input id="query" type="text" name="query" style="width:500px">
    <input class="fancyButton" type="submit" value="OK">
</form>
{% for post in posts %}
<div class="post_box" onclick='location.href="{% url 'forum:post' post.id %}";'>
    <h2>{{post.title}}</h2>
    <p><i>By {{post.author}} on {{post.created}}</i></p>
    <p>{% with broken=post.content|linebreaks %}{{broken|truncatechars:300}}{% endwith %}</p>
    <p>——<br><i>{{post.views}} views</i>
    {% if post.agreechecks > 0 %} &ensp;•&ensp; <i>{% widthratio agrees agreechecks 100 %}% agree with this</i> {% endif %}
    {% if post.strongchecks > 0 %} &ensp;•&ensp; <i>{% widthratio strongs strongchecks 100 %}% think this was a strong argument</i> {% endif %}
    </p>
    </div>
<br>
{% endfor %}
{% endblock %}

forum/templates/write_post.html
{% extends 'base.html' %}

{% block content %}
{% include "navbar.html" %}
<h1>Write a Post</h1>
<form name="myForm" action="{% url 'forum:write_post' %}" method="POST">
    {% csrf_token %}
    <p>Post title: {{ form.title }}</p>
    <p>Post content: (min length 2000 char, max 20000)<br>{{ form.content }}</p>
    <input type="submit" class="fancyButton" value="Submit" onclick="return checkForm();" style="font-size: large">
</form>
{% endblock %}