OpenDialogue/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
import OpenDialogue.views as core_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', core_views.home, name='home'),
    path('authentication/', include('authentication.urls'), name='authentication'),
    path('forum/', include('forum.urls'), name='forum')
]

OpenDiscussion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
import OpenDiscussion.views as core_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', core_views.home, name='home'),
    path('authentication/', include('authentication.urls'), name='authentication'),
    path('forum/', include('forum.urls'), name='forum'),
    path('about/', core_views.about, name='about')
]

authentication/urls.py
from django.urls import path

from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'authentication'
urlpatterns = [
    path('login', LoginView.as_view(template_name="login.html"), name='login'),
    path('signup', views.signup, name='signup'),
    path('logout', LogoutView.as_view(next_page='home'), name='logout'),
]

forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'
urlpatterns = [
    path('', views.index, name='index'),
    path('write_post', views.write_post, name='write_post'),
    path('respond_post/<postid>', views.respond_post, name='respond_post'),
    path('post_successful', views.post_successful, name='post_successful'),
    path('post/<postid>', views.post, name='post'),
    path('agree/<postid>', views.agree, name='agree'),
    path('disagree/<postid>', views.disagree, name='disagree'),
    path('strong/<postid>', views.strong, name='strong'),
    path('weak/<postid>', views.weak, name='weak'),
    path('explore', views.explore, name='explore'),
    path('account/<searchusername>', views.account, name='account'),
]

templates/about.html
{% extends 'base.html' %}

{% block content %}
<div class="ulGray" style="margin: 0px calc(-3/14*100%); position:sticky; top:0; z-index: 2">
    <div style="margin: 0px 15%">
        <li style="float: left;{% if current_page == "index" %}background-color:#676;{% endif %}"><a href="{% url 'forum:index' %}">Recommended</a></li>
        <li style="float: left;{% if current_page == "write_post" %}background-color:#676;{% endif %}"><a href="{% url 'forum:write_post' %}">Write a post</a></li>
        <li style="float: left;{% if current_page == "explore" %}background-color:#676;{% endif %}"><a href="{% url 'forum:explore' %}">Explore</a></li>
        <li style="float: right; color: white; padding: 10px 16px"><div class="theme-switch-wrapper">
            <label class="theme-switch" for="checkbox">
                <input type="checkbox" id="checkbox" />
                <div class="slider round"></div>
            </label>
            <div style="font-style: normal;">&ensp;☾</div>
        </div>
        </li>
    </div>
</div>
<h1>About Us</h1>
<h2>Mission</h2>
<p><i>OpenDiscussion</i> is a forum website designed to promote safe, high-quality discussions between opposing ideas.</p>
<p>Online spaces often struggle with three interlacing problems:</p>
<ol>
    <li style="padding: 5px 0px;"><b>Echo chambers:</b> Online spaces often degenerate into echo chambers, where people end up only exposed to ideas that they agree with, radicalizing them. Sometimes, censorship can aid in this, as censorship might asymmetrically reduce exposure to certain opinions.</li>
    <li style="padding: 5px 0px;"><b>Safety and quality:</b> On the other end of the spectrum, a complete lack of censorship or moderation can lead to unsafe discussions or poor-quality posting.</li>
</ol>
<p><i>OpenDiscussion</i>'s purpose is to try and provide an online forum that addresses these issues--to provide a forum that is safe and high-quality without resorting to censorship.</p>
<h2>Highlighted Features</h2>
<ul>
    <li style="padding: 5px 0px;"><b>Posts:</b> Users can write and upload posts to our forum. Posts have a minimum length of 2000 characters (~300 words) in order to promote more thought-out posts.</li>
    <li style="padding: 5px 0px;"><b>Upvote system:</b> Instead of a generic upvote/downvote system, we have specific agreement & strength voting. Users vote individually on whether they agree with a post and whether they think a post makes a strong argument.</li>
    <li style="padding: 5px 0px;"><b>Responding to posts:</b> Instead of comments, you respond to posts with your own post. Thus, instead of brief superficial comments, to respond to a post you are encouraged to make your own well-thought-out argument.</li>
    <li style="padding: 5px 0px;"><b>Recommended posts feed:</b> The landing page for the user is a recommended posts feed, where you receive 5 posts daily that <i>OpenDiscussion</i> recommends reading. The site prioritizes high strength, high controversiality posts.</li>
</ul>
{% endblock %}

templates/base.html
{% load static %}

<html>
    <head>
        <title>OpenDiscussion</title>
        <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
        <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
    </head>
    <body>
        <div style="min-height: calc(100vh - 175px);">
            <a href="{% url 'home' %}" style="text-decoration: none;"><h1 style="text-align: center; font-weight: normal; font-size:48px;">🌿 OpenDiscussion&ensp;&ensp;&ensp;</h1></a>
            <br>
            {% block content %}
            {% endblock %}
        </div>
        <script type="text/javascript" src="{% static 'main.js' %}"></script>
    </body>
    <footer>
        <p><a style="text-decoration: none;" href="{% url 'home' %}">OpenDiscussion.org</a> • <a style="text-decoration: none;" href="{% url 'about' %}">About Us</a><br>Brandon Lee, 2021</p>
    </footer>
</html>

templates/home.html
{% load static %}

<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">   
        <title>OpenDiscussion</title>
        <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">         
    </head>
    <body style="background-image: url('{% static 'background2.jpg' %}'); background-size: cover; background-repeat:no-repeat">
        <div class="container"><div class="center">
            <div class="fancyShadeBox" style="text-align:center; width: 800px; height: 400px; padding: 50px;">
                <center>
                <br>
                <div style="color:green; font-size:72px;">🌿 OpenDiscussion&ensp;</div>
                <p>Welcome to OpenDiscussion.org, the space for constructive free speech.</p>
                <br>
                <div class="fancyButton" style="width: 200px; font-size: 20px;" onclick='location.href="{% url 'authentication:login' %}";'>Log In</div>
                <br>
                <div class="fancyButton" style="width: 200px; font-size: 20px;" onclick='location.href="{% url 'authentication:signup' %}";'>Sign Up</div>
                </center>
            </div>
        </div></div>
        <div style="text-align:center; bottom:30px;">Brandon Lee, 2021 • <a style="text-decoration: none;" href="{% url 'about' %}">About Us</a></div>
    </body>
</html>

templates/navbar.html
{% block content %}
<div class="ulGray" style="margin: 0px calc(-3/14*100%); position:sticky; top:0; z-index: 2">
    <div style="margin: 0px 15%">
        <li style="float: left;{% if current_page == "index" %}background-color:#676;{% endif %}"><a href="{% url 'forum:index' %}">Recommended</a></li>
        <li style="float: left;{% if current_page == "write_post" %}background-color:#676;{% endif %}"><a href="{% url 'forum:write_post' %}">Write a post</a></li>
        <li style="float: left;{% if current_page == "explore" %}background-color:#676;{% endif %}"><a href="{% url 'forum:explore' %}">Explore</a></li>
        <li style="float: right;"><a href="{% url 'authentication:logout' %}">Log out</a></li>
        <li style="float: right;"><a href="{% url 'forum:account' user.username %}">Logged in as {{ user.username }}</a></li>
        <li style="float: right; color: white; padding: 10px 16px"><div class="theme-switch-wrapper">
            <label class="theme-switch" for="checkbox">
                <input type="checkbox" id="checkbox" />
                <div class="slider round"></div>
            </label>
            <div style="font-style: normal;">&ensp;☾</div>
        </div>
        </li>
    </div>
</div>
{% endblock %}